[package]
name = "basicjwt"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
hmac = "0.12.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sha2 = "0.10.8"
