[package]
name = "basicjwt"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
rsa = { version = "0.9.8", features = ["sha2"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
